Repository thisandagain/sentiment, pull requests merged in 2019-08, with the labels that each got.

#169 Update dependencies
  package.json
Labels: greenkeeper

#149 Fix for replacing punctuation in tokenize.js
  lib/tokenize.js
  test/integration/sync_corpus.js
  test/unit/tokenize.js
Labels: pr - needs review

#154 Typo on #160, #164
  README.md
Labels: pr - good to merge

#167 Escape question mark
  lib/tokenize.js
Labels: pr - good to merge

#161 Added calculation breakdown into results
  README.md
  lib/index.js
Labels: pr - good to merge
